### ISSUE TITLE
consulting expert

### ISSUE THREAD

**Issue by Lucarda** [Lucarda/pd-hidraw#1]
@Spacechild1 when you have time can you review: https://github.com/Lucarda/pd-hidraw/blob/8cb9844eb33b179c63a0c58e7ecfd5ba40a9db2d/pd-hidraw.c#L182

Does this output need to be in a `clock` ?

**Comment by Spacechild1** [comment]
Is `hidraw_poll` called by the user Pd message? Then you just output the result.

If you want `hidraw_poll` to be called periodically within the object, the whole function must be scheduled with a clock.

**Comment by Lucarda** [comment]
got it. Thanks.

**Comment by Lucarda** [comment]
@Spacechild1  I think i'm ready for a deken release (no hurries). When you have time can you review?

**Comment by Spacechild1** [comment]
Hey, I'm in a big production until October 9, but afterwards I have time! In case I forget, just bump me :-)

**Comment by Lucarda** [comment]
ok, no trouble.

:)

**Comment by Lucarda** [comment]
> In case I forget, just bump me :-)

Hoping your production went well. If you can (no rushes from my side) please review.

**Comment by Lucarda** [comment]
@Spacechild1  I'm planning to release soon. can you review if you have time?

If you can't no trouble. may be for the next (bug) release.

**Comment by Spacechild1** [comment]
I have a 10 hour train ride next Wednesday where I have plenty of time. I'll take a note so I don't forget.

**Comment by Lucarda** [comment]
I couldn't wait longer and went ahead releasing v0.1.0.

May be later you can review for a possible bug fix. 

closing for now.
