### ISSUE TITLE
Pull in `hidapi` as a Git submodule?

### ISSUE THREAD

**Issue by aaaaalbert** [Lucarda/pd-hidraw#2]
(Note: This is not a bug nor a feature request, just a suggestion to maybe make updating the codebase easier in the future.)

I noticed you manually copied over some files and directories from https://github.com/libusb/hidapi into the `hidapi` subdirectory of your repo and documented the commit hash at the time of copying. This is all fine, I understand that you probably don't want to clutter your repo with all of `hidapi` etc.

However, once you want to update `hidapi`, you will need to redo the manual selection and copying process. It might be easier to declare `hidapi` a *Git Submodule* of your repo so that it is automatically included from the original repo at the speficified version / commit hash.

If you want to know more about the Git Submodule approach, check [this example](https://github.com/githubtraining/example-dependency) and the [Git docs](https://git-scm.com/book/en/v2/Git-Tools-Submodules). I can also send you a PR with the required change. Just let me know.

If not, feel free to close the issue -- things are fine the way they are :-)

**Comment by Lucarda** [comment]
Hi @aaaaalbert

The main reason I don't use the Git Submodule approach is this commit https://github.com/Lucarda/pd-hidraw/commit/0f820adf701d0c1314a0e3aca68086272d3338e0 to `hidapi/hidapi/hidapi.h` which is badly needed for the Windows object.

I could have a patch file that runs on build but this way is more simple and also, as you said, I don't want to clutter the repo.

Thanks for your suggestion!

:)

**Comment by aaaaalbert** [comment]
Oh, I missed that patch! The submodule-less approach sure makes sense then, thanks for explaining.

**Comment by Lucarda** [comment]
Reopening for myself:

When I find time try to use `hidapi` as a submodule and inject this into the setup function:

```
#if defined(_WIN32)
__declspec(dllexport)
#else
__attribute__((visibility("default")))
#endif
void hidraw_setup(void) {
```

**Comment by Lucarda** [comment]
done via 0981c06

Closing.
